<main class="app-main">
    <div class="app-content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <h3 class="mb-0"><?= htmlspecialchars($pageTitle) ?></h3>
                </div>
                <?= $breadcrumbsHtml ?>
            </div>
        </div>
    </div>
    <div class="app-content">
        <div class="container-fluid">